### ISSUE TITLE
Crash when you click on the buttons "saved, daily level and featured"

### ISSUE THREAD

**Issue by mattop147** [geode-sdk/NodeIDs#106]
When I click on the buttons "saved, featured and daily level" my game crash but it doesn't crash when I click on the other buttons in the menu Can you help me solve the problem pls ?

This is the crash logs :

2024-10-25T15:05:38+0200
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.8.1
Loader Commit: 47e0ca5
Bindings Commit: 7fbb83d
Installed mods: 37
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FFF11377356 (Geode.dll + 47356 (cocos2d::CCNode::setID + 38 | /home/runner/work/geode/geode/loader/src/hooks/GeodeNodeMetadata.cpp:121))
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 47356 (cocos2d::CCNode::setID + 38 | /home/runner/work/geode/geode/loader/src/hooks/GeodeNodeMetadata.cpp:121)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + 6e20b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + 6c7a6
 - 000001E621760882 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\itzkiba.grandpa_demon\itzkiba.grandpa_demon.dll + 247d1
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\itzkiba.grandpa_demon\itzkiba.grandpa_demon.dll + a4df
 - 000001E621760882 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + abf97
 - 000001E621760C82 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + c6798
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + 6c4fb
 - 000001E621760C82 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + a96a4
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3b631
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 73bcc
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + a9d25
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3b465
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + a86e6
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2b85b5
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2b9090
 - 000001E637400482 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\itzkiba.grandpa_demon\itzkiba.grandpa_demon.dll + 24558
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\itzkiba.grandpa_demon\itzkiba.grandpa_demon.dll + 951f
 - 000001E637400482 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2b7e63
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2b6b41
 - 000001E621760482 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + c64f8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + 69f23
 - 000001E621760482 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\itzkiba.grandpa_demon\itzkiba.grandpa_demon.dll + 23f58
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\itzkiba.grandpa_demon\itzkiba.grandpa_demon.dll + 91ca
 - 000001E621760482 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2b5797
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 9b869
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 597cf (cocos2d::CCMenuItem::activate + 47)
 - 000001E6212F0882 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 45725 (geode::modifier::AsStaticFunction_activate<hook7<(anonymous namespace)::hook7Parent>,void (hook7<(anonymous namespace)::hook7Parent>::*)()>::Impl<void (hook7<(anonymous namespace)::hook7Parent>::*)()>::function + 21 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenuItem.hpp:35)
 - 000001E6212F0882 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 58798 (cocos2d::CCMenu::ccTouchEnded + 40)
 - 000001E6212F0C82 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 45def (geode::modifier::AsStaticFunction_ccTouchEnded<hook15<(anonymous namespace)::hook15Parent>,void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::Impl<void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::function + 47 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenu.hpp:105)
 - 000001E6212F0C82 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + b0c3c (cocos2d::CCTouchDispatcher::touches + 444)
 - 000001E621733482 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\tobyadd.gdh\tobyadd.gdh.dll + 91ca8
 - 000001E621733482 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 6b131 (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 97)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 76159 (cocos2d::CCEGLView::onGLFWMouseCallBack + 249)
 - 000001E62176D48B (Hook handler)
 - 000001E62176D48B (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 76186
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + d686b
 - C:\Windows\System32\USER32.dll + 183f1
 - C:\Windows\System32\USER32.dll + 17c3b (CallWindowProcW + 139)
 - C:\Windows\SYSTEM32\OPENGL32.dll + 41eb4
 - C:\Windows\System32\USER32.dll + 183f1
 - C:\Windows\System32\USER32.dll + 17eb1
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + d4198
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72ca6 (cocos2d::CCApplication::run + 1078)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2910da (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:181)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\Windows\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\Windows\SYSTEM32\ntdll.dll + 5af08 (RtlUserThreadStart + 40)

== Register States ==
RAX: 0000000000000000
RBX: 0000000000000000
RCX: 0000000000000000
RDX: 00000084ed8fd160
RBP: 0000000000000000
RSP: 00000084ed8ffea0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007fffbe2aaf08
R8:  0000000000000000
R9:  000001e6529025e0
R10: fefefefefefefeff
R11: 8080808080808080
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v1.0.3] alphalaneous.awesome_modifier_icons
  | [v1.0.5] alphalaneous.improved_group_view
  | [v1.0.8] alphalaneous.improvedlink
  | [v1.5.5] alphalaneous.integratedloquibot
  | [v1.3.1] alphalaneous.pages_api
x | [v1.0.4] alphalaneous.twitch_chat
  | [v1.1.12] b1rtek.gddlintegration
  | [v1.8.3] beat.click-sound
x | [v1.2.5] blueblock6.cleanstartpos
  | [v1.0.7] cdc.level_thumbnails
  | [v4.2.11] cvolton.betterinfo
x | [v1.0.1] cvolton.level-id-api
x | [v1.2.1] cvolton.misc_bugfixes
  | [v1.6.2] dankmeme.globed2
x | [v1.0.9] firee.goldenbest
x | [v0.3.2] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.9.0] geode.custom-keybinds
x | [v3.8.1] geode.loader
x | [v1.15.0] geode.node-ids
x | [v1.6.2] geode.texture-loader
x | [v1.1.0] hjfod.backups
  | [v6.8.0] hjfod.betteredit
  | [v1.0.0] hjfod.bettersave_recovery
x | [v1.2.1] hjfod.gmd-api
  | [v1.0.0] hjfod.trashcan
  | [v1.2.1] itzkiba.better_progression
x | [v1.2.0] itzkiba.grandpa_demon
x | [v1.0.0] m336.autoleaderboard
  | [v1.1.0] m336.modbadgeinfo
x | [v1.2.0] mat.circle-tool
  | [v1.0.0-beta.45] minemaker0430.gddp_integration
x | [v1.1.4] ninkaz.blending_glow
  | [v2.1.0] spaghettdev.gd-roulette
  | [v1.0.4] thesillydoggo.icon_kit_switcher
x | [v4.7.7] tobyadd.gdh
x | [v1.2.1] uproxide.autosong

**Comment by Cvolton** [comment]
happens if your texture pack is missing the ncs icon - get a texture pack that's updated for 2.206 to fix this properly

otherwise this is fixed in 2aef314d4ed7803b2285466960b23453e2bd9d8f (upcoming 1.15.1 update)
