### ISSUE TITLE
Game crash on pause - MacOS

### ISSUE THREAD

**Issue by TeemSucks** [geode-sdk/NodeIDs#11]
[2024-02-09_23-11-07.log](https://github.com/geode-sdk/NodeIDs/files/14227902/2024-02-09_23-11-07.log)
Geometry dash crashed when pausing the game on macOS

<img width="257" alt="Screenshot 2024-02-09 at 23 14 59" src="https://github.com/geode-sdk/NodeIDs/assets/88513373/e6627cd8-5e85-4a06-a96d-5e530f10f958">

**Comment by Cvolton** [comment]
fixed in b33556548287885a01d0c7ba1e0469a54f1dfafd (Node IDs update 1.4.0)
