### ISSUE TITLE
group id edit page is broken when sepecting multiple objects

### ISSUE THREAD

**Issue by Kingminer7** [geode-sdk/NodeIDs#12]
![Screenshot_20240215_150958_Geode](https://github.com/geode-sdk/NodeIDs/assets/100500023/3caf1100-3802-4d4c-9ed7-616a8a14015f)
when selecting multiple objects, the group id page gets arranged wrong.

my guess is that the wrong id is set because the editor removes certain buttons if multiple objects are selected. then, when nodeids sets the layout, it moves some of the buttons to the wrong spots.

**Comment by TheSillyDoggo** [comment]
How did it even move the extra down there

**Comment by abeljakowoff** [comment]
also, if group id's are added, the group id buttons will not display correctly after re-entering the edit group menu

![image](https://github.com/geode-sdk/NodeIDs/assets/70239841/7595770c-815b-4f04-9cdf-c8202b67694d)

**Comment by Allentothemax12** [comment]
same

**Comment by HJfod** [comment]
fixed in 1.5.1
