### ISSUE TITLE
Edit group screen is broken

### ISSUE THREAD

**Issue by InfernuZGD** [geode-sdk/NodeIDs#14]
All buttons work, but you can't type in the values

**Comment by silvernull** [comment]
I am also having this issue,
it is also noted in:
https://discord.com/channels/911701438269386882/1207892414337912872

I cannot type into the edit group text boxes.

**Comment by BlaccEye23** [comment]
I also have this specific issue. 
Cant type in any numbers to edit groupt text boxes.

**Comment by relaxingOcean** [comment]
same here, hate it so much

**Comment by matcool** [comment]
fixed in 1.6.0
