### ISSUE TITLE
(BUG) Adding Groups is broken

### ISSUE THREAD

**Issue by BlaccEye23** [geode-sdk/NodeIDs#16]
When you select objects and edit the groups and finally want to type in a group number you want to assign, it does not work.
What happens is that when you click on the box to write a number to assign a group, the selection is blocked and you cant type any number at all. When this specific mod is disabled, writing group numbers in the box works perfectly fine again.

Please fix as soon as you can.
Thank you very much.

**Comment by Spidapida** [comment]
It seems like the edit object wasn't engaging completely---any text inputs in that are not responsive to that, but keyboard shortcuts like free move, snap to grid, and other key shortcuts in editor still work

**Comment by matcool** [comment]
this was already fixed in 1.6.0
