### ISSUE TITLE
I can't writing a group number

### ISSUE THREAD

**Issue by Lanalanita** [geode-sdk/NodeIDs#17]
https://github.com/geode-sdk/NodeIDs/assets/108598436/ab7bdfff-630a-47f6-8cdc-341d5acd570d

since I updated node ids, this part of the editor does not work
Not anymore, it was fixed in version 1.6

**Comment by YraXxx** [comment]
yeah im having this same issue

**Comment by matcool** [comment]
fixed in 1.6.0
