### ISSUE TITLE
"Node IDs has failed unzipping"

### ISSUE THREAD

**Issue by PlayMakeReview** [geode-sdk/NodeIDs#18]
For some reason, when I updated Node IDs the other day, it did not unzip. There was no crash, it just didn't load. The "More" message says: "Unable to delete temp dir: Access is denied". I have no clue how to fix this.

**Comment by Cvolton** [comment]
Geode issue rather than Node IDs, the usual fix is to restart your PC

**Comment by geodeproblemsnnnn** [comment]
i have problems i tried restarting my pc but it didnt work it says node id cant be unzipped:unable to. how to fix it?
