### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by vsirOG** [geode-sdk/NodeIDs#21]
![Screenshot 2024-02-18 204248](https://github.com/geode-sdk/NodeIDs/assets/160444910/72a513a5-d035-4f5d-aa1b-cae8ed6b7736)

**Comment by B1rtek** [comment]
windows defender probably removed the dll, check protection history and click allow

**Comment by vsirOG** [comment]
So i removed geode and reinstalled the new version. guess geode wasn't updating correctly.
