### ISSUE TITLE
EditorUI is still broken

### ISSUE THREAD

**Issue by abeljakowoff** [geode-sdk/NodeIDs#23]
UI in Edit Group window can be broke when objects with several group ids are selected. Perhaps this bug happens only with [BetterEdit](https://github.com/HJfod/BetterEdit) mod, which change this window with new ui objects. 

![image](https://github.com/geode-sdk/NodeIDs/assets/70239841/015af4a9-c573-4d4f-976c-a77f341174cd)

_actually idk where I should create this problem but I did it here_

**Comment by abeljakowoff** [comment]
seems like issue was solved after BetterEdit mod update

**Comment by abeljakowoff** [comment]
EditorUI still broken after BetterEdit mod v6.3.3 update. Bug happens on NodeIDs v1.6.1
![image](https://github.com/geode-sdk/NodeIDs/assets/70239841/5a55271e-4dfb-47f0-acde-f51df11cafbc)

**Comment by matcool** [comment]
fixed in 1.7.0
