### ISSUE TITLE
Edit Object Layering Bug

### ISSUE THREAD

**Issue by Zoroa621** [geode-sdk/NodeIDs#24]
On Android, when you Copy Values of an object and go into Edit Object with more than one object selected, the Paste button for the colors is overlapping the Browse button, making it almost impossible to use. I uninstalled all the mods except for the Node IDs to see if it was being caused from a specific mod, to which it was only having the Node IDs installed that causes it. Hopefully this gets fixed soon.
![Screenshot_20240223-032833_Geode](https://github.com/geode-sdk/NodeIDs/assets/159903575/08e1f956-35f6-4c86-b48a-984b819ab14f)

**Comment by slammy333** [comment]
Can confirm this happens on Windows as well w/ node IDs v1.6.1

**Comment by Cvolton** [comment]
confirmed to still be an issue in 1.9.0

**Comment by NualLight** [comment]
Pls fix this is happening again

**Comment by Cvolton** [comment]
fixed in the upcoming 1.13.0 release 93e29665c04cb90908357147ee6dc34bd922ed68
