### ISSUE TITLE
Crashing when i press play on a level 100% of the time EVEN STEREO MADNESS DONT WORK.

### ISSUE THREAD

**Issue by VaNdraRat** [geode-sdk/NodeIDs#26]
After updateing node ids i met my self playing a level and when i press play i crash. even on main level PLS FIX THIS.

**Comment by matcool** [comment]
cant recreate imo, pretty unhelpful issue

**Comment by VaNdraRat** [comment]
Unhelpfull.. I cant even play the game now (imo meaning?)

**Comment by RayDeeUx** [comment]
@VaNdraRat hello, there was a slight miscommunication somewhere down the line

give it a few minutes, [this commit](https://github.com/geode-sdk/NodeIDs/commit/caecfd527038f233ba7e60860457d919f923e9e5) should fix it

**Comment by VaNdraRat** [comment]
Ok :D

**Comment by Cvolton** [comment]
caused by some other mods expecting a different node ID for UILayer, this has been changed to the expected one in 1.7.1
