### ISSUE TITLE
Unable to load the DLL

### ISSUE THREAD

**Issue by KylomaskGamer** [geode-sdk/NodeIDs#32]
![image](https://github.com/geode-sdk/NodeIDs/assets/83834554/a5a9960b-6cc9-4aa3-a83c-0f209decc833)

there was a problem and i was told to report this

Unable to load the DLL: ERROR_PROC_NOT_FOUND; The mod tried to access a function defined in another DLL, but the specified function was not found. Make sure the other DLL exports the given symbol, and that it is defined in the DLL. If you are not the developer of this mod, report this error to them as it is likely not your fault.

also im on a windows 11

**Comment by Cvolton** [comment]
make sure your geode is up to date - beta 22

**Comment by KylomaskGamer** [comment]
> make sure your geode is up to date - beta 22

ok

**Comment by KylomaskGamer** [comment]
alright nvm its fixed thanks @Cvolton
