### ISSUE TITLE
node ids cant unzip

### ISSUE THREAD

**Issue by Ev212** [geode-sdk/NodeIDs#35]
tried to open the game but it says node ids cant unzip which means that i cant play geometry dash with geode

<img width="1919" alt="image" src="https://github.com/geode-sdk/NodeIDs/assets/78379509/1829f244-a750-4124-bbba-8b76a17d1b9f">
<img width="1919" alt="image" src="https://github.com/geode-sdk/NodeIDs/assets/78379509/54efb4f7-1fcd-47f9-960f-a749a90a6f1c">

**Comment by Cvolton** [comment]
click more to see more info, if it says "access denied", restart your pc to fix

**Comment by Ev212** [comment]
ok thank you!

**Comment by enessmr** [comment]
oh
