### ISSUE TITLE
game not loading

### ISSUE THREAD

**Issue by Corrodere211** [geode-sdk/NodeIDs#42]
idk if this is just happening to me but when i install node ids my game wont start and will be stuck on "loading game resources"
![Uploading image_2024-04-12_172816601.png…]()

**Comment by Cvolton** [comment]
are you running the latest geode version? (beta.23 as of the time of writing)

**Comment by RB-999** [comment]
> are you running the latest geode version? (beta.23 as of the time of writing)

It crashes on Geode beta.26

**Comment by enderprism** [comment]
i'm experiencing the same issue with geode beta.27
geometry dash is running under Proton 9.0-1 on my endeavourOS system
node ids version: [v1.11.0](https://github.com/geode-sdk/NodeIDs/releases/tag/v1.11.0)

[Geode 2024-05-27 23.16.16.log](https://github.com/geode-sdk/NodeIDs/files/15461837/Geode.2024-05-27.23.16.16.log)

**Comment by hiimjustin000** [comment]
That's the wrong log. Go to the crashlogs folder.

**Comment by enderprism** [comment]
the game doesn’t actually crashes. it freezes after loading and stays like that until i force-close it.

**Comment by enderprism** [comment]
i'll try changing proton versions

**Comment by RoootTheFox** [comment]
highly unlikely that its a linux issue - but try using GloriousEggrolls' Proton-GE, thats what im running

**Comment by enderprism** [comment]
that's what i tried and it didn't fix it

**Comment by Cvolton** [comment]
does the issue still happen on geode 3.x and gd 2.206?

**Comment by enderprism** [comment]
it doesn't happen anymore on my end
