### ISSUE TITLE
it doesnt work in UI

### ISSUE THREAD

**Issue by DuyCDed** [geode-sdk/NodeIDs#51]
It bugs and it doesn't receive any mod that has a UI

**Comment by Alphalaneous** [comment]
If it says Node IDs failed to unzip, try restarting the device, 
if it says to enable it, go to the mod in Geode and enable it, 
if it says to update it, go to the mod in Geode and update it

**Comment by DuyCDed** [comment]
I enabled it but it doesn't work after resetting It says error

**Comment by Mark-3010** [comment]
, пытаюсь включить мод а он не работает выключишь не включишь а если включишь и перезапустишь просто не работает
