### ISSUE TITLE
It´s not opening

### ISSUE THREAD

**Issue by OrfiGD** [geode-sdk/NodeIDs#55]
i uploaded the mod and now at the menu of the game it just appears the logo and it sais "upload the mod NodeID´s for playing" (here is a screenshot)
![Captura de pantalla 2024-05-13 154204](https://github.com/geode-sdk/NodeIDs/assets/169713522/490dee27-64d9-445f-9d8e-934af9d1ee1c)

**Comment by RoootTheFox** [comment]
well, update node ids

**Comment by OrfiGD** [comment]
> well, update node ids

did it, but nothing changed

**Comment by RoootTheFox** [comment]
is there still an update available? if so, update

**Comment by OrfiGD** [comment]
> is there still an update available? if so, update

no it´s up to date, but i have the exact error, here it is:
![imagen_2024-05-13_160759563](https://github.com/geode-sdk/NodeIDs/assets/169713522/19292002-9b13-4f76-b6b7-2e0d681942ae)

**Comment by RoootTheFox** [comment]
(alternatively, look for any Geometry Dash or Geode related processes in Task Manager and kill them)
