### ISSUE TITLE
Crashing when I search

### ISSUE THREAD

**Issue by ViniviosGD** [geode-sdk/NodeIDs#59]
When I enable Node IDS for some mods or just enable without mods It crashes when I click the search button it crashes
[Geode 2024-05-17 18.21.43.log](https://github.com/geode-sdk/NodeIDs/files/15344604/Geode.2024-05-17.18.21.43.log)
[Geode 2024-05-17 18.22.14.log](https://github.com/geode-sdk/NodeIDs/files/15344606/Geode.2024-05-17.18.22.14.log)
[Geode 2024-05-17 18.22.24.log](https://github.com/geode-sdk/NodeIDs/files/15344608/Geode.2024-05-17.18.22.24.log)

the crashlogs if you need it

**Comment by cootshk** [comment]
Same thing happening for me (M2 Mac)

**Comment by Cvolton** [comment]
does the issue still happen on the latest version?
