### ISSUE TITLE
Icon Kit Bug

### ISSUE THREAD

**Issue by Wave6767** [geode-sdk/NodeIDs#62]
The UI in the Icon Kit is messed-up on Android (32-bit)
![Uploading Screenshot_20240522_214831_Geode.jpg…]()

**Comment by RayDeeUx** [comment]
i dont think the screenshot went through, try again

**Comment by Wave6767** [comment]
> i dont think the screenshot went through, try again

Thanks.

**Comment by Wave6767** [comment]
The pic will not work. Here is a YT vid for it: https://youtu.be/YS3Mt9ELd3Q?si=Qc_aDxpXCoqw7pnX

**Comment by matcool** [comment]
icon save bug, not node id
