### ISSUE TITLE
2.206

### ISSUE THREAD

**Issue by Moody761** [geode-sdk/NodeIDs#68]
Geode isnt opening because Node IDs has an issue and I don't know what it is but it's broken since **2.206** released

**Comment by EjkiCat** [comment]
WHAT DO I DO HELLPPPPPP

**Comment by TheSillyDoggo** [comment]
All mods are broken in 2.206.

**Comment by JoaoBoladin** [comment]
> All mods are broken in 2.206.

Not all of them. Circle Tool, Click Sounds, Minecraft Menu and some other ones work. But the majority of mods are broken (including, obviously, Node IDs)
