### ISSUE TITLE
The 2.206 fix doesn't show up

### ISSUE THREAD

**Issue by NoodleNut** [geode-sdk/NodeIDs#70]
Idk if it's just my android but, I saw the 2.206 fix but when I go to geode there's no update, I'm assuming you forgot to update it on android, you can take this as a reminder.

**Comment by iArtie** [comment]
No, it's because geode doesn't have an update yet that version 2.206 supports, when there is it will be notified on the geode server, I recommend you to be aware of it

**Comment by NoodleNut** [comment]
> No, it's because geode doesn't have an update yet that version 2.206 supports, when there is it will be notified on the geode server, I recommend you to be aware of it

Thanks
