### ISSUE TITLE
Nodes not working

### ISSUE THREAD

**Issue by Saryps** [geode-sdk/NodeIDs#75]
When I enable the mod it fails to enable so I can't use a lot of mods like better edit.
![Screenshot_2024-06-04-07-51-59-889_com geode launcher](https://github.com/geode-sdk/NodeIDs/assets/171651675/18c40d0a-c5b3-4aa1-8362-3fd82e664430)
This is a photo, and also Im on android

**Comment by KelFloppy** [comment]
Same here
Same error

**Comment by x-Z0RrY-x** [comment]
Also :(

**Comment by jrocknthehouse** [comment]
Not to be annoying with this message, but is this problem being looked into or being figured out? 👍

**Comment by Alphalaneous** [comment]
You do know 2.206 released and every mod is going to be broken until they are ported which will take time. It’s not a bug, but the nature of modding. The 2.206 version of geode is being worked on and once that’s ready, you will start to see mods being updated.

**Comment by jrocknthehouse** [comment]
Oh okay sorry. 👍
