### ISSUE TITLE
Mod doesnt load on 2.206 of geometry dash 

### ISSUE THREAD

**Issue by IanLuzbel** [geode-sdk/NodeIDs#78]
Hello, i wanted to report that geometry dash 2.206 with NodeIDs have a bug that makes the mod doesnt load and some mods cant load because NodeIDs is required.
So can you fix this because i need to load mods that makes the game more fun. Thanks

**Comment by Ducgdgames** [comment]
Cả mod globed nhiều người chơi và QOL mod menu cũng ko load được

**Comment by Ducgdgames** [comment]
Vẫn có một số mod có thể load trên geometry dash 2.2.142
Nhưng những mod menu và nodeids với rất nhiều mod khác đều không thể load được
Tôi mong nhà phát hành geode sửa lại lỗi này
![Screenshot_20240605-163030_Geode](https://github.com/geode-sdk/NodeIDs/assets/171533219/0f67f6b7-9f71-4baf-a144-c5ae020e370e)
![Screenshot_20240605-163027_Geode](https://github.com/geode-sdk/NodeIDs/assets/171533219/53c35c5e-37f4-4027-9078-1dbbb93c8a25)
![Screenshot_20240605-163042_Geode](https://github.com/geode-sdk/NodeIDs/assets/171533219/036b8c1e-86b9-4880-927c-b18c671b6d19)
![Screenshot_20240605-163039_Geode](https://github.com/geode-sdk/NodeIDs/assets/171533219/d254169d-9713-47ec-b9a4-10ce605eb2ee)
