### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Ickkcknfggf** [geode-sdk/NodeIDs#80]
When you enter to geode it says "download the node IDs mod" but if you install it doesn't work 
![Screenshot_20240605-145733](https://github.com/geode-sdk/NodeIDs/assets/171870446/1dd8a45a-b079-4aff-966b-eb6b54f75b15)

**Comment by Geodeplayer1** [comment]
I have it downloaded but it just stopped working after having it downloaded for 4 weeks

**Comment by Cvolton** [comment]
see #84
