### ISSUE TITLE
Node ids problem

### ISSUE THREAD

**Issue by Mechagodzilla170** [geode-sdk/NodeIDs#81]
It keeps telling me to install node ids even tho I have it installed

**Comment by JoaoBoladin** [comment]
It's broken. Node IDs doesn't work in 2.206. And they might be fixing it (I need it fixed because all my data is in geode and I can't access and save it to load in regular gd)

**Comment by Fleeym** [comment]
We're working on porting Geode and all the related mods to 2.206, please be patient.

**Comment by Mechagodzilla170** [comment]
Oh ok,good luck!
