### ISSUE TITLE
Unable to load the SO: dlerror

### ISSUE THREAD

**Issue by Yunasha** [geode-sdk/NodeIDs#82]
nodeID refuses to load because its failed to locate a symbol.

happened on the latest gd version 2.206
[Geode 2024-06-06 10.03.45.log](https://github.com/user-attachments/files/15599134/Geode.2024-06-06.10.03.45.log)
![Screenshot_2024_0606_081002](https://github.com/geode-sdk/NodeIDs/assets/88642958/8aa05706-2334-4c29-bb9c-627c60cbdeda)

**Comment by hiimjustin000** [comment]
Node IDs does not support Geometry Dash 2.206.

**Comment by Cvolton** [comment]
see #84
