### ISSUE TITLE
GD Update 2.206 broke Node IDs: Mod doesn't load

### ISSUE THREAD

**Issue by Cvolton** [geode-sdk/NodeIDs#84]
Since 2.206 came out, Node IDs mod doesn't load. This is a known issue - all mods will have to be updated, including Geode itself.

![image](https://github.com/geode-sdk/NodeIDs/assets/5721187/6a367498-dabb-4caa-9976-8153806e362e)

Android users can still load some 2.204 mods, however only the ones that don't change anything that was changed in the update work. Since Node IDs affects stuff that changed in the update, you need to wait until the 2.206 version of Geode is finished, which will hopefully be very soon.

Also if you see a huge screen telling you to enable Node IDs instead of getting in-game, disable the Click Sounds mod.

**Comment by JoaoBoladin** [comment]
Even the BetterInfo creator wants it to be fixed

**Comment by JoaoBoladin** [comment]
BRO I JUST READ THAT LAST SENTENCE THANK YOU SO MUCH CVOLTON

**Comment by Geodefan** [comment]
That's the same issue I'm going thru I tried litteraly unstilled everything mods I had and didn't work

**Comment by Cvolton** [comment]
update's out, problem resolved

**Comment by yomamamamamama** [comment]
i tried to install Node IDs but it said "unable to delete temp dir: access is denied" please help

**Comment by Geodefan** [comment]
WHAT
