### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Red-impostorYT** [geode-sdk/NodeIDs#9]
When i start gd it is not enabled and there is ! next to it idk and alot of mods are not working because of it 
![Screenshot 2024-02-08 190700](https://github.com/geode-sdk/NodeIDs/assets/130860976/1b3728a2-894b-4a3e-90a6-8b8dd821e722)
![Screenshot 2024-02-08 190704](https://github.com/geode-sdk/NodeIDs/assets/130860976/e3bb37a2-7af1-44be-bf4b-386a5c0d11c5)
![Screenshot 2024-02-08 190710](https://github.com/geode-sdk/NodeIDs/assets/130860976/825c9acf-5ff3-47b7-b60f-1a22e869e68b)
![Screenshot 2024-02-08 190723](https://github.com/geode-sdk/NodeIDs/assets/130860976/746e3feb-a187-405b-8648-2fc701d612b4)
![Screenshot 2024-02-08 190728](https://github.com/geode-sdk/NodeIDs/assets/130860976/296efeaf-1a54-4c25-be7c-0202025d9a5e)
![Screenshot 2024-02-08 190742](https://github.com/geode-sdk/NodeIDs/assets/130860976/28ff2a57-8d5e-4e50-845f-e737a38da23d)
![Screenshot 2024-02-08 190751](https://github.com/geode-sdk/NodeIDs/assets/130860976/b637f1af-7520-40e4-b481-150dc760542c)
and it crashes when i open my profile 
[2024-02-08_19-09-48.log](https://github.com/geode-sdk/NodeIDs/files/14215835/2024-02-08_19-09-48.log)
yeah idk why...

**Comment by Cvolton** [comment]
update click sounds mod

**Comment by Cvolton** [comment]
also the crash is from cleanermenu
